name: all_process
'on':
   schedule:
    - cron: '0 22 * * *'
   workflow_dispatch: # 添加一个可以手动运行的按钮
jobs:
  process_bot:
    runs-on: ubuntu-latest
    steps:
      - name: check_code
        uses: actions/checkout@master
      - name: set up Python 3.9
        uses: actions/setup-Python@v4
        with:
          python-version: '3.9'
      - name: install requirements
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install requests
          pip install requests_toolbelt
          pip install bs4
          pip install pillow
          pip install selenium
          pip install webdriver-manager
          pip install seaborn
          pip install pyautogui
          pip install pdfplumber
          pip install sklearn
      - name: process data
        run: python ./code/global_code/all_process.py
      - name: commit and push if it changed
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Last updated on: ${timestamp}" || exit 0
          git push
  upload_bot:
    needs: process_bot
    runs-on: windows-latest
    steps:
      - name: check_code
        uses: actions/checkout@master
      - name: set up Python 3.9
        uses: actions/setup-Python@v4
        with:
          python-version: '3.9'
      - name: install requirements
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install bs4
          pip install pillow
          pip install selenium
          pip install webdriver-manager
          pip install seaborn
          pip install pyautogui
      - name: process data
        run: python ./code/global_code/auto_upload.py
