name: all_process
'on':
   schedule:
    - cron: '0 22 */3 * *'
   workflow_dispatch: # 添加一个可以手动运行的按钮
jobs:
  process_bot:
    runs-on: ubuntu-latest
    steps:
      - name: check_code
        uses: actions/checkout@v3
      - name: set up Python 3.10
        uses: actions/setup-Python@v4
        with:
          python-version: '3.10'
      - name: install requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install packaging
      - name: process data
        run: python ./code/global_code/all_process.py
      - name: commit and push if it changed
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git add -A
          timestamp=$(date -u)
          git commit -m "Last updated on: ${timestamp}" || exit 0
          git push
