name: create_requirements
'on':
   schedule:
    - cron: '0 20 */3 * *'
   workflow_dispatch: # 添加一个可以手动运行的按钮
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Self test
        id: selftest

        uses: ryan-rozario/pipreqs-action-cpy@master

        # Put an example of mandatory inputs here
        with:
          PROJECT_PATH: .
          REQUIREMENT_PATH: ./requirements.txt  #default is requirement.txt in the root of your repository 
