name: all_process
'on':
  schedule:
    - cron: '0 22 1-10 * *'
  workflow_dispatch: # 添加一个可以手动运行的按钮
jobs:
  upload_bot:
    runs-on: windows-latest
    steps:
      - name: check_code
        uses: actions/checkout@master
      - name: set up Python 3.8
        uses: actions/setup-Python@v2
        with:
          python-version: '3.8'
      - name: install requirements
        run: |
          python -m pip install --upgrade pip
          pip install pandas
          pip install bs4
          pip install pillow
          pip install selenium
          pip install webdriver-manager
          pip install seaborn
          pip install pyautogui
      - name: process data
        run: python ./code/global_code/auto_upload.py
